### ISSUE TITLE
Javascript error thrown in storefront instance context

### ISSUE THREAD

**Issue by royteeuwen** [adobe/aem-cif-guides-venia#209]
### Expected Behaviour
No javascript errors thrown
### Actual Behaviour

The following error occurs when opening the venia site on publish instance through a dispatcher that is configured to go to a magento cloud instance

```
Could not fetch storefront instance context Error: Cannot query field "dataServicesStorefrontInstanceContext" on type "Query".
    at new t (clientlib-site.js:705)
    at clientlib-site.js:705
    at r (clientlib-site.js:705)
    at clientlib-site.js:705
    at new Promise (<anonymous>)
    at Object.then (clientlib-site.js:705)
    at Object.next (clientlib-site.js:705)
    at O (clientlib-site.js:705)
    at E (clientlib-site.js:705)
    at e.t.next (clientlib-site.js:705)
```

#### Platform and Version
AEM 6.5.9 (on-premise in Azure)
Docker Dispatcher: https://github.com/adobe/aem-core-cif-components/tree/master/dispatcher
Adobe Commerce AddOn 2021 10 05
aem-cif-guides-venia main branch

**Comment by Buuhuu** [comment]
This is an issue related to your Adobe Commerce installation. See the answers to https://stackoverflow.com/questions/69044508/getting-error-with-venia-code-after-integrated-magento-with-aem-as-a-cloud-servi/69151701 and https://stackoverflow.com/questions/69008839/aem-venia-store-category-and-product-page-data-not-fetching

**Comment by royteeuwen** [comment]
Super, thanks!
