### ISSUE TITLE
Frontend Maven Plugin Error during code deployment in Windows

### ISSUE THREAD

**Issue by Arpitha1405** [adobe/aem-cif-guides-venia#238]
### Expected Behaviour
The code build should be SUCCESS

### Actual Behaviour
Venia - UI Frontend module is failing with errors

### Steps to Reproduce

        1.  Clone the Venia Project Codebase
        2.  Run the command **mvn clean install** on the project root directory.
        3.  UI Frontend module gets failed with the following error:         
       
           
<img width="630" alt="Error1" src="https://user-images.githubusercontent.com/67728005/148556785-46345699-64c1-4940-b605-de492431d8af.PNG">

        4.  The error that caused to fail the frontend module is **[ERROR] 'rm' is not recognized as an internal or external 
             command**
         
<img width="618" alt="Error2" src="https://user-images.githubusercontent.com/67728005/148556803-fbd83525-a275-4933-b80d-d23cf8422338.png">

        5. The command that fails is the **i18n:extract-compile** build script from package.json
        "i18n:extract-compile": "formatjs extract --out-file i18n/__temp.json 'src/**/*.js' && formatjs compile --ast --out-file 
         i18n/en.json i18n/__temp.json && **rm i18n/__temp.json**"

        6. When debugged the 'rm' command error, a few articles mention about using either 'del' or 'rd' command in place of rm.
        Reference1 - 
       
<img width="280" alt="ArticleRef1" src="https://user-images.githubusercontent.com/67728005/148557100-3df4523f-ad01-45c6-b5a3-5d7b6621b418.PNG">

       Reference2 -
       https://reactgo.com/rm-command-not-recognized/
       
<img width="582" alt="ArticleReference" src="https://user-images.githubusercontent.com/67728005/148556991-01f617c8-c2ae-4312-b88c-a2094a156f2c.PNG">

        7. If we update the command with 'del' or 'rd' we get the below error:
     
<img width="618" alt="Error3" src="https://user-images.githubusercontent.com/67728005/148556719-cf4dea0d-3b46-4bb4-ae01-f15abf0836aa.png">

 
#### Attached the screenshots along with the steps for reference.

Hi @mhaack, 
Kindly help to resolve this issue.

Best Regards,
Arpitha

**Comment by mhaack** [comment]
Thanks @Arpitha1405 for reporting this. Since you already analysed the root cause, do you mind creating a PR?

**Comment by Buuhuu** [comment]
@adobe export to Jira Project CIF as Bug

**Comment by Arpitha1405** [comment]
@mhaack -
The above-mentioned points are the steps that I tried to debug with.
But even if we update the build script "i18n:extract-compile" by replacing **rm** with **del**, the build is failing.
Would need your help to resolve the build issue.

**Comment by Buuhuu** [comment]
@Arpitha1405 I created a PR #239 ... can you verify that this change resolves the issue for you?

**Comment by Arpitha1405** [comment]
@Buuhuu - The changes are working fine. Thank you for the quick help!
<img width="676" alt="BuildSuccess" src="https://user-images.githubusercontent.com/67728005/148764673-6ba5ca37-1f8f-47ac-bc34-7912bebea77d.png">




Just wanted to mention one thing, when I tried to deploy the branch https://github.com/adobe/aem-cif-guides-venia/tree/issue/gh-238 directly in my local, I got the below error:
**[ERROR] Failed to execute goal on project aem-cif-guides-venia.core: Could not resolve dependencies for project com.adobe.aem.guides:aem-cif-guides-venia.core:jar:2021.12.02-SNAPSHOT: Failure to find com.adobe.commerce.cif:core-cif-components-core:jar:2.4.3-SNAPSHOT in https://repo.adobe.com/nexus/content/groups/public/ was cached in the local repository, resolution will not be reattempted until the update interval of adobe-public-releases has elapsed or updates are forced -> [Help 1]**
<img width="673" alt="CIF_jar_error_in_branch-issue-gh-238" src="https://user-images.githubusercontent.com/67728005/148764656-a4e7a545-44dd-4862-83c6-0ef434216d67.PNG">
Is the above error expected if we deploy any of the sub-branches in our local machine?

Hence, I manually updated the changes mentioned in the PR to the previously cloned repository i.e. **main** branch.

**Comment by Buuhuu** [comment]
Thanks for confirming.

The `main` branch refers always to a released version of the [CIF Core Components](https://github.com/adobe/aem-core-cif-components/releases), `dev` and any other feature branch however may refer to the current development iteration, which means they use a SNAPSHOT of the CIF Core Components.

You may want to clone the the CIF Core Components, build the latest master yourself and retry the build of Venia afterwards.

**Comment by Arpitha1405** [comment]
Sure, Thank you for the confirmation.
